kubernetes:
  accounts:
  - name: armory-sales-dev
    serviceAccount: true
  # Add your accounts here, /kubeconfigfiles is the path where kubeconfig files added
  # to kustomization.yaml are mounted.
#  - kubeconfigFile: /kubeconfigfiles/kubecfg-test.yml
#    name: account1
#    metrics: false
#    kinds: []
#    omitKinds: []

clouddriver:
  #grpc: a6c62a609c4924be895e64f789166519-fa66194008d74fde.elb.us-west-2.amazonaws.com:9091
  #insecure: true
  #grpc: kubesvc-vincent.se.armory.io:443
  grpc: vincent-clouddriver.se.armory.io:443
  insecure: false

server:
  port: 8082
  
prometheus:
  enabled: true
  # port: 8008
