# This produces a deployment for kubesvc standalone
resources:
- deployment.yaml

namespace: kubesvc

configMapGenerator:
- files:
  - kubesvc.yaml
  name: kubesvc-config
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: armory/kubesvc
  newTag: 0.2.0-rc.51
