apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker  # name doesn't matter since this is a patch
spec:
  spinnakerConfig:
    profiles:
      gate:
        security:
          basicform:
            enabled: true
          user:
            name: spinnaker
            password: armorySpinnaker2020
        server:
          tomcat:
            protocolHeader: X-Forwarded-Proto
            remoteIpHeader: X-Forwarded-For
            internalProxies: .*
            httpServerPort: X-Forwarded-Port
