apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      deploymentEnvironment:
        customSizing:
          clouddriver:
            limits:
              cpu: 2
              memory: 4Gi
            requests:
              cpu: 500m
              memory: 1Gi
          deck: 
            limits:
              cpu: 300m
              memory: 64Mi
            requests:
              cpu: 150m
              memory: 64Mi
          dinghy: 
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 128Mi
          echo:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 256Mi
          fiat:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 128Mi
          front50:
            limits:
              cpu: 300m
              memory: 1Gi
            requests:
              cpu: 150m
              memory: 512Mi
          gate:
            limits:
              cpu: 600m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 512Mi
          kayenta:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          igor:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          orca:
            limits:
              cpu: 1
              memory: 1Gi
            requests:
              cpu: 750m
              memory: 512Mi
          rosco:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          terraformer:
            limits:
              cpu: 300m
              memory: 512Mi
            requests:
              cpu: 150m
              memory: 256Mi
          redis:
            limits:
              cpu: 750m
              memory: 1Gi
            requests:
              cpu: 300m
              memory: 256Mi