apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
    config:
      providers:
        kubernetes:
          enabled: true
          accounts:
            - name: gke-pocs
              kubeconfigFile: encryptedFile:k8s!n:spin-secrets!k:kubeconfig-gke
              onlySpinnakerManaged: false
          primaryAccount: gke-pocs
