apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-clouddriver-rw
  name: spin-clouddriver-ha-grpc
spec:
  ports:
    - name: grpc
      port: 9091
      protocol: TCP
      targetPort: 9091
  selector:
    app: spin
    cluster: spin-clouddriver-rw
