apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vincent 

commonAnnotations:
  kustomizePath: "vincent/kustomization.yml"
  owner: "se team"

bases:
- ../base

patchesStrategicMerge:
- patch-persistentStore.yml # s3 bucket
- patch-providers-k8s.yml # using serviceAccounts
- patch-version.yml # spinnaker Version
- patch-endpoint.yml # vincent.se.armory.io and gate endpoint: api/v1/
- patch-auth.yml # github oauth
- patch-customhooksnjobs.yml # custom terraform enterprise stages
- patch-mysql.yml # mysql clouddriver
- patch-redis.yml
- patch-validation.yml
- patch-aws-lambda.yml  # add lambda plugin and enable lambda
- patch-kubesvc-plugin.yml  # both patch files required for kubesvc
- patch-clouddriver-plugin.yml  # both patch files required for kubesvc
- patch-bitbucket.yml
- patch-policyengine.yml  # 0.2.1
