apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      orca:
        webhook:
          preconfigured:
          - label: TFE Apply
            type: tfeapply
            enabled: true
            description: Terraform Enterprise Apply stage
            method: POST
            customHeaders:
              Authorization:
                - encrypted:k8s!n:tfcloud-armory-sales!k:bearertoken
              Content-Type:
                - application/vnd.api+json
            url: https://${parameterValues['TFE_ADDR']}/api/v2/runs/${parameterValues['RUN_ID']}/actions/apply
            payload: |-
              {
                "comment": "${parameterValues['comment']}"
              }
            parameters:
              - label: TFE Address 
                name: TFE_ADDR
                description: Endpoint for TFE
                defaultValue: app.terraform.io
                type: string
              - label: RUN ID
                name: RUN_ID
                description: Retrieve the RUN ID from the Plan
                type: string
              - label: Comment
                name: comment
                type: string
          - label: TFE Discard
            type: tfediscard
            enabled: true
            description: Terraform Enterprise Discard (cancel) stage
            method: POST
            customHeaders:
              Authorization:
                - encrypted:k8s!n:tfcloud-armory-sales!k:bearertoken
              Content-Type:
                - application/vnd.api+json
            url: https://${parameterValues['TFE_ADDR']}/api/v2/runs/${parameterValues['RUN_ID']}/actions/discard
            payload: |-
              {
                "comment": "${parameterValues['comment']}"
              }
            parameters:
              - label: TFE Address 
                name: TFE_ADDR
                description: Endpoint for TFE
                defaultValue: app.terraform.io
                type: string
              - label: RUN ID
                name: RUN_ID
                description: Retrieve the RUN ID from the Plan
                type: string
              - label: Comment
                name: comment
                type: string
        job:
          preconfigured:
            kubernetes:
              - label: TFE Plan
                type: tfeplan
                description: Terraform Enterprise Plan
                cloudProvider: kubernetes
                account: spinnaker
                credentials: spinnaker
                waitForCompletion: true
                consumeArtifactSource: propertyFile
                propertyFile: terraformplan
                application: tfe
                parameters:
                  - name: artifact
                    label: Artifact Account
                    description: '#toJson(trigger.artifacts.^[type=="git/repo"])'
                    mapping: manifest.spec.template.spec.containers[0].env[4].value
                    defaultValue: '${#toJson(trigger.artifacts.^[type=="git/repo"])}'
                  - name: subdirectory
                    label: subdirectory
                    description: the folder where main.tf resides
                    mapping: manifest.spec.template.spec.containers[0].env[5].value
                  - name: bucketname
                    label: Bucket Name
                    description: for demo 
                    mapping: manifest.spec.template.spec.containers[0].env[6].value
                  - name: tfe_org
                    label: TFE Organization
                    mapping: manifest.spec.template.spec.containers[0].env[1].value
                  - name: tfe_addr
                    label: TFE Address
                    mapping: manifest.spec.template.spec.containers[0].env[2].value  
                    description: app.terrform.io
                    defaultValue: "app.terraform.io"
                  - name: tfe_workspace
                    label: TFE Workspace
                    mapping: manifest.spec.template.spec.containers[0].env[3].value
                manifest:
                  apiVersion: batch/v1
                  kind: Job
                  metadata:
                    name: terraformplan
                  spec:
                    template:
                      spec:
                        containers:
                        - name: terraformplan
                          image: away168/tfe:v0.3.0
                          # ARGUMENTS:
                          # bucketname
                          command:
                          - ./terraformplan.sh
                          # ENVIRONMENT VARIABLES req'd
                          # TFE_TOKEN
                          # TFE_ORG 
                          # TFE_ADDR (optional) default: "app.terraform.io"
                          # WORKSPACE 
                          # ARTIFACT_SERVICE (optional) default: "http://spin-clouddriver:7002"
                          # ARTIFACT_JSON use SpEL, e.g. `#toJson(artifact)`
                          # SUBDIRECTORY - where main.tf resides inside git repo
                          env:
                          - name: TFE_TOKEN
                            value: encrypted:k8s!n:tfcloud-armory-sales!k:token
                          - name: TFE_ORG
                            value: placeholder
                          - name: TFE_ADDR
                            value: placeholder
                          - name: WORKSPACE
                            value: placeholder
                          - name: ARTIFACT_JSON
                            value: placeholder
                          - name: SUBDIRECTORY
                            value: placeholder
                          - name: BUCKET_NAME
                            value: placeholder
                          #- name: ARTIFACT_SERVICE
                          #  value: "http://spin-clouddriver:7002"
                        restartPolicy: Never
                    backoffLimit: 1
              - label: StackHawk HawkScan
                type: hawkscan
                description: Application security scan
                cloudProvider: kubernetes
                account: spinnaker
                credentials: spinnaker
                waitForCompletion: true
                #consumeArtifactSource: propertyFile
                #propertyFile: hawkscan
                application: hawkscan
                parameters:
                  - name: repo
                    label: Repo URL
                    description: https://github.com/zconger/hawk-armory.git
                    mapping: manifest.spec.template.spec.containers[0].env[0].value
                    defaultValue: https://github.com/zconger/hawk-armory.git
                  - name: environment
                    label: Environment
                    description: the environment for scanning
                    mapping: manifest.spec.template.spec.containers[0].env[1].value
                    defaultValue: Development
                  - name: host
                    label: APP HOST
                    description: the URL of the app to scan
                    mapping: manifest.spec.template.spec.containers[0].env[2].value
                    defaultValue: http://rps.dev
                manifest:
                  apiVersion: batch/v1
                  kind: Job
                  metadata:
                    name: hawkscan
                    namespace: spinnaker
                  spec:
                    backoffLimit: 0
                    template:
                      spec:
                        containers:
                          - env:
                              - name: REPO_URL
                                value: 'https://github.com/zconger/hawk-armory.git'
                              - name: APP_ENV
                                value: Development
                              - name: APP_HOST
                                value: http://rps.dev
                              - name: API_KEY
                                value: encrypted:k8s!n:stackhawk!k:apikey
                              - name: REPO_DIR
                                value: /home/zap/workdir
                            command:
                              - /bin/bash
                              - '-c'
                              - |
                                git clone $REPO_URL $REPO_DIR
                                shawk
                            image: 'stackhawk/hawkscan:0.8.26'
                            name: hawkscan
                        restartPolicy: Never
                    ttlSecondsAfterFinished: 600
