apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      # Configs in the spinnaker profile get applied to all services
      spinnaker:
        armory:
          policyEngine:
            opa:
              # Replace with the actual URL to your Open Policy Agent deployment
              baseUrl: http://opa.opa.svc.cluster.local:8181/v1
              # Optional. The number of seconds that the Policy Engine will wait for a response from the OPA server. Default is 10 seconds if omitted.
              # timeoutSeconds: <integer> 
        spinnaker:
          extensibility:
            repositories:
              policyEngine:
                enabled: true
                url: https://raw.githubusercontent.com/armory-plugins/policy-engine-releases/master/repositories.json
      gate:
        spinnaker:
          extensibility:
            plugins:
              Armory.PolicyEngine:
                enabled: true
            deck-proxy:
              enabled: true
              plugins:
                Armory.PolicyEngine:
                  enabled: true
                  version: &version 0.2.1

      orca:
        spinnaker:
          extensibility:
            plugins:
              Armory.PolicyEngine:
                enabled: true
                version: *version

      front50:
        spinnaker:
          extensibility:
            plugins:
              Armory.PolicyEngine:
                enabled: true
                version: *version

      clouddriver:
        spinnaker:
          extensibility:
            plugins:
              Armory.PolicyEngine:
                enabled: true
                version: *version
      # the spinnaker profile will be applied to all services
      # spinnaker:
      #   armory:
      #     policyEngine:
      #       opa:
      #         # this should be replaced with the actual URL to your Open Policy Agent deployment
      #         baseUrl: http://opa.opa:8181/v1/data

      #   spinnaker:
      #     extensibility:
      #       repositories:
      #         policyEngine:
      #           enabled: true
      #           # the init container will install plugins.json to this path.
      #           url: file:///opt/spinnaker/lib/local-plugins/policy-engine/plugins.json
      # gate:
      #   spinnaker:
      #     extensibility:
      #       plugins:
      #         Armory.PolicyEngine:
      #           enabled: true

      # orca:
      #   spinnaker:
      #     extensibility:
      #       plugins:
      #         Armory.PolicyEngine:
      #           enabled: true

      # front50:
      #   spinnaker:
      #     extensibility:
      #       plugins:
      #         Armory.PolicyEngine:
      #           enabled: true

      # clouddriver:
      #   spinnaker:
      #     extensibility:
      #       plugins:
      #         Armory.PolicyEngine:
      #           enabled: true
  # kustomize:
  #   front50:
  #     deployment:
  #       patchesStrategicMerge:
  #         - |
  #           spec:
  #             template:
  #               spec:
  #                 initContainers:
  #                   - name: policy-engine-install
  #                     image: armory/policy-engine-plugin:v0.0.19
  #                     imagePullPolicy: Always
  #                     args:
  #                       - -install-path
  #                       - /opt/policy-engine-plugin/target
  #                     volumeMounts:
  #                       - mountPath: /opt/policy-engine-plugin/target
  #                         name: policy-engine-plugin-vol
  #                   containers:
  #                     - name: front50
  #                       volumeMounts:
  #                         - mountPath: /opt/spinnaker/lib/local-plugins
  #                           name: policy-engine-plugin-vol
  #                   volumes:
  #                     - name: policy-engine-plugin-vol
  #                       emptyDir: {}
  #   orca:
  #     deployment:
  #       patchesStrategicMerge:
  #         - |
  #           spec:
  #             template:
  #               spec:
  #                 initContainers:
  #                   - name: policy-engine-install
  #                     image: armory/policy-engine-plugin:v0.0.19
  #                     imagePullPolicy: Always
  #                     args:
  #                       - -install-path
  #                       - /opt/policy-engine-plugin/target
  #                     volumeMounts:
  #                       - mountPath: /opt/policy-engine-plugin/target
  #                         name: policy-engine-plugin-vol
  #                   containers:
  #                     - name: orca
  #                       volumeMounts:
  #                         - mountPath: /opt/spinnaker/lib/local-plugins
  #                           name: policy-engine-plugin-vol
  #                   volumes:
  #                     - name: policy-engine-plugin-vol
  #                       emptyDir: {}
  #   gate:
  #     deployment:
  #       patchesStrategicMerge:
  #         - |
  #           spec:
  #             template:
  #               spec:
  #                 initContainers:
  #                   - name: policy-engine-install
  #                     image: armory/policy-engine-plugin:v0.0.19
  #                     imagePullPolicy: Always
  #                     args:
  #                       - -install-path
  #                       - /opt/policy-engine-plugin/target
  #                     volumeMounts:
  #                       - mountPath: /opt/policy-engine-plugin/target
  #                         name: policy-engine-plugin-vol
  #                   containers:
  #                     - name: gate
  #                       volumeMounts:
  #                         - mountPath: /opt/spinnaker/lib/local-plugins
  #                           name: policy-engine-plugin-vol
  #                   volumes:
  #                     - name: policy-engine-plugin-vol
  #                       emptyDir: {}
    ## MOVE TO CLOUDDRIVER-PLUGIN.yml
    # clouddriver:
    #   deployment:
    #     patchesStrategicMerge:
    #       - |
    #         spec:
    #           template:
    #             spec:
    #               initContainers:
    #                 - name: policy-engine-install
    #                   image: armory/policy-engine-plugin:v0.0.19
    #                   imagePullPolicy: Always
    #                   args:
    #                     - -install-path
    #                     - /opt/policy-engine-plugin/target
    #                   volumeMounts:
    #                     - mountPath: /opt/policy-engine-plugin/target
    #                       name: policy-engine-plugin-vol
    #                 containers:
    #                   - name: clouddriver
    #                     volumeMounts:
    #                       - mountPath: /opt/spinnaker/lib/local-plugins
    #                         name: policy-engine-plugin-vol
    #                 volumes:
    #                   - name: policy-engine-plugin-vol
    #                     emptyDir: {}
