apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      clouddriver:
        kubesvc:
          cluster: redis
          grpc:
            server:
              security:
                enabled: true
                certificateChain: file:///opt/clouddriver/cert/tls.crt    #list of crts
                trustCertCollection: file:///opt/clouddriver/cert/tls.crt #cacert
                privateKey: file:///opt/clouddriver/cert/tls.key
                clientAuth: OPTIONAL #REQUIRE
#          eventsCleanupFrequencySeconds: 7200
#          localShortCircuit: false
#          runtime:
#            defaults:
#              onlySpinnakerManaged: true
#            accounts:
#              account1:
#                customResources:
#                  - kubernetesKind: MyKind.mygroup.acme
#                    versioned: true
#                    deployPriority: "400"
