apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      version: 2.21.4  # NOTE: when using armory agent (kubesvc) plugin - we need to match the two versions.