## AFTER SETTING UP THE DB
## create the users: clouddriver_service and clouddriver_migrate
## CREATE USER 'clouddriver_service'@'%' IDENTIFIED BY 'password'
## CREATE USER 'clouddriver_migrate'@'%' IDENTIFIED BY 'password'
## THEN FOLLOW DOCS: https://spinnaker.io/setup/productionize/persistence/clouddriver-sql/
apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      clouddriver:
        sql:
          enabled: true
          # read-only boolean toggles `SELECT` or `DELETE` health checks for all pools.
          # Especially relevant for clouddriver-ro and clouddriver-ro-deck which can
          # target a SQL read replica in their default pools.
          read-only: false
          taskRepository:
            enabled: true
          cache:
            enabled: true
            # These parameters were determined to be optimal via benchmark comparisons
            # in the Netflix production environment with Aurora. Setting these too low
            # or high may negatively impact performance. These values may be sub-optimal
            # in some environments.
            readBatchSize: 500
            writeBatchSize: 300
          scheduler:
            enabled: false  # flip flop with redis.scheduler.enabled
          connectionPools:
            default:
              # additional connection pool parameters are available here,
              # for more detail and to view defaults, see:
              # https://github.com/spinnaker/kork/blob/master/kork-sql/src/main/kotlin/com/netflix/spinnaker/kork/sql/config/ConnectionPoolProperties.kt
              default: true
              jdbcUrl: jdbc:mysql://mariadb:3306/clouddriver
              user: clouddriver_service
              password: encrypted:k8s!n:mariadb-clouddriver!k:password
            # The following tasks connection pool is optional. At Netflix, clouddriver
            # instances pointed to Aurora read replicas have a tasks pool pointed at the
            # master. Instances where the default pool is pointed to the master omit a
            # separate tasks pool.
            # tasks:
            #   user: clouddriver_service
            #   jdbcUrl: jdbc:mysql://mariadb:3306/clouddriver
            #   password: encrypted:k8s!n:mariadb-clouddriver!k:password
          migration:
            user: clouddriver_migrate
            jdbcUrl: jdbc:mysql://mariadb:3306/clouddriver
            password: encrypted:k8s!n:mariadb-clouddriver!k:password
        redis:
          enabled: true
          connection: redis://spin-redis.vincent:6379
          cache:
            enabled: false
          scheduler:
            enabled: true  # if you have issues, try enabling redis and this flag: scheduler.
          taskRepository:
            enabled: false

