apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        apiSecurity:
          ssl:
            enabled: false
          overrideBaseUrl: https://vincent.se.armory.io/api/v1
          corsAccessPattern: https://vincent.se.armory.io
        uiSecurity:
          ssl:
            enabled: false
          overrideBaseUrl: https://vincent.se.armory.io
    profiles:
      gate:
        server:
          servlet:
            context-path: /api/v1
    service-settings:
      gate:
        healthEndpoint: /api/v1/health
