apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      spinnaker:
        spinnaker:
          extensibility:
            plugins:
              Armory.PolicyEngine:
                enabled: true
                version: 0.0.12
                extensions:
                  armory.policyEngine:
                    enabled: true
                    config:
                      opa:
                        baseUrl: http://opa.opa:8181/v1
            repositories:
              armory:
                url: https://raw.githubusercontent.com/armory-plugins/policy-engine-releases/master/repositories.json
        armory.policyEngine.opa.baseUrl: http://opa.opa:8181/v1
      # front50:
      #   spinnaker:
      #     extensibility:
      #       plugins:
      #         Armory.PolicyEngine:
      #           enabled: true
      #           version: 0.0.12
      #           extensions:
      #             armory.policyEngine:
      #               enabled: true
      #               config:
      #                 opa: 
      #                   baseUrl: http://opa.opa:8181/v1
      #       repositories:
      #         armory:
      #           url: https://raw.githubusercontent.com/armory-plugins/policy-engine-releases/master/repositories.json
      # orca:
      #   spinnaker:
      #     extensibility:
      #       plugins:
      #         Armory.PolicyEngine:
      #           enabled: true
      #           version: 0.0.12
      #           extensions:
      #             armory.policyEngine:
      #               enabled: true
      #               config:
      #                 opa: 
      #                   baseUrl: http://opa.opa:8181/v1
      #       repositories:
      #         armory:
      #           url: https://raw.githubusercontent.com/armory-plugins/policy-engine-releases/master/repositories.json