apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      clouddriver:
        spinnaker:
          extensibility:
            pluginsRootPath: /opt/clouddriver/lib/plugins
            plugins:
              Armory.Kubesvc:
                enabled: true
  kustomize:
    clouddriver:
      service:
        patchesStrategicMerge:
          - |
            spec:
              ports:
                - name: http
                  port: 7002
                - name: grpc
                  port: 9091
      deployment:
        patchesStrategicMerge:
          - |
            spec:
              template:
                spec:
                  initContainers:
                  - name: kubesvc-plugin
                    image: docker.io/armory/kubesvc-plugin:0.6.2
                    volumeMounts:
                      - mountPath: /opt/plugin/target
                        name: kubesvc-plugin-vol
                  - name: policy-engine-install
                    image: armory/policy-engine-plugin:v0.0.19
                    imagePullPolicy: Always
                    args:
                      - -install-path
                      - /opt/policy-engine-plugin/target
                    volumeMounts:
                      - mountPath: /opt/policy-engine-plugin/target
                        name: policy-engine-plugin-vol
                  containers:
                  - name: clouddriver
                    volumeMounts:
                      - mountPath: /opt/clouddriver/lib/plugins
                        name: kubesvc-plugin-vol
                      - mountPath: /opt/clouddriver/cert
                        name: cert
                      - mountPath: /opt/spinnaker/lib/local-plugins
                        name: policy-engine-plugin-vol
                  volumes:
                  - name: kubesvc-plugin-vol
                    emptyDir: {}
                  - name: cert
                    secret:
                      secretName: vincent-clouddriver-agent-v3
                  - name: policy-engine-plugin-vol
                    emptyDir: {}