kind: Namespace
apiVersion: v1
metadata:
  name: agent
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-role
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: agent-operator
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-operator-binding
subjects:
- kind: ServiceAccount
  name: agent-operator
  namespace: agent
roleRef:
  kind: ClusterRole
  name: agent-role
  apiGroup: rbac.authorization.k8s.io
---
kind: Secret
apiVersion: v1
metadata:
  name: kubeconfigs-secret