#To Test the Machine Learning Model Use the Curl Command with your external endpoint FQDN inputting an image URL from the internet.  The /predict request will input the image to the ML model which has been trained and return result
#It uses the CIFAR-10 dataset of 60,000 images in 10 classes with the Gluon library in Apache MXNet and NVIDIA GPUs to accelerate the workload
#
#curl -X POST -d '{"url": "https://i.imgur.com/jD2hDMc.jpg"}' -H 'Content-Type: application/json' http://<your-cluster's-ip>/predict
#
apiVersion: v1
kind: Namespace
metadata:
  name: ml-kube
  labels:
    name: staging
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ml-kube
  labels:
    app: image-classifier
  name: image-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: image-classifier
  template:
    metadata:
      labels:
        app: image-classifier
    spec: 
      containers:
      - image: 'ctripod/keras-app:latest'
        name: image-classifier
        port:
          -containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  namespace: ml-kube
  labels:
    app: image-classifier
  name: image-classifier
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: image-classifier
  type: LoadBalancer
