apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: spinnaker 

commonAnnotations:
  kustomizePath: "/etc/spinnaker/kustomize/julius"

bases:
- ../base

patchesStrategicMerge:
- patch-auth.yml
- patch-providers-k8s.yml # using serviceAccounts
- patch-version.yml # spinnaker Version
- patch-endpoint.yml # vincent.se.armory.io and gate endpoint: api/v1/
- patch-version.yml
- patch-stats.yml
