apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vincent 

commonAnnotations:
  kustomizePath: "/etc/spinnaker/kustomize/vincent"

bases:
- ../base

resources:
#- ingress.yaml

patchesStrategicMerge:
- patch-providers-k8s.yml # using serviceAccounts
- patch-version.yml # spinnaker Version
- patch-endpoint.yml # vincent.se.armory.io and gate endpoint: api/v1/
- patch-redis.yml # use spinnaker redis
- patch-policyengine.yml 
- patch-version.yml
#- ingress.yaml
