apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/app-protocols: '{"grpc":"HTTP2"}'
  labels:
    app: spin
    cluster: spin-clouddriver
  name: spin-clouddriver-headless
  namespace: spinnaker
spec:
  ports:
  - name: grpc
    port: 9091
    protocol: TCP
    targetPort: 9091
  selector:
    app: spin
    cluster: spin-clouddriver
  sessionAffinity: None
  type: LoadBalancer
