apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress
  labels:
    app: "spin"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    # nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  rules: []
