apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: spinnaker
  namespace: spinnaker
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
spec:
  rules:
  - host: spin.armory.garreeoke.io
    http:
      paths:
      - backend:
          serviceName: spin-deck
          servicePort: 9000
        path: /
      - backend:
          serviceName: spin-gate
          servicePort: 8084
        path: /api
  tls:
  - hosts:
    - spin.armory.garreeoke.io
    secretName: spin-armory-garreeoke-io
