apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: spinnaker
  namespace: spinnaker
spec:
  rules:
    - host: deck.spin.armory.garreeoke.io
      http:
        paths:
          - backend:
              serviceName: spin-deck
              servicePort: 9000
    - host: gate.spin.armory.garreeoke.io
      http:
        paths:
          - backend:
              serviceName: spin-gate
              servicePort: 8084
