apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  notes: "The configuration files reside in a git repo : https://github.com/armory/se-spinnaker-config"

resources:
- spinnakerservice.yml
#- ingress.yml ///TODO: revisit later - may just use spec.expose when it supports ingresses

patchesStrategicMerge:
- patch-componentsizing.yml # custom resource limits & requests
- patch-persistentStore.yml # s3 bucket
- patch-provider-docker.yml # away168 docker registry
- patch-features.yml # UI Artifact Rewrite / Kustomize
- patch-slack.yml
- patch-jenkins.yml 
- patch-github.yml
- patch-dinghy.yml
- patch-terraform.yml 
- patch-canary.yml
- patch-aws.yml
- patch-s3artifact.yml
- patch-helm.yml

