apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  notes: "The configuration files reside in a pvc mounted to the terminal-0 pod under /etc/spinnaker"

resources:
- spinnakerservice.yml
#- ingress.yml ///TODO: revisit later - may just use spec.expose when it supports ingresses

patchesStrategicMerge:
- patch-persistentStore.yml # s3 bucket
- patch-provider-docker.yml # away168 docker registry
- patch-features.yml # UI Artifact Rewrite / Kustomize
- patch-slack.yml
- patch-jenkins.yml 
- patch-github.yml
#- patch-auth.yml # github login
#- patch-dinghy.yml
#- patch-terraform.yml 
#- patch-aws.yml

