apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonAnnotations:
  notes: "The configuration files reside in a git repo : https://github.com/armory/se-spinnaker-config"

resources:
- spinnakerservice.yml

#bases:
#- agent-service

patchesStrategicMerge:
- patch-componentsizing.yml # custom resource limits & requests
#- patch-expose.yml
- patch-gate.yml
- patch-annotations.yml
- patch-persistentStore.yml # gcs bucket
- patch-provider-k8s.yml
- patch-provider-docker.yml
- patch-policyengine.yml
- patch-features.yml # UI Artifact Rewrite / Kustomize
- patch-github.yml
- patch-dinghy.yml
- patch-terraform.yml
- patch-vault.yml
- patch-logging.yml # Turn on debug logging
- patch-canary.yml # Canary google config
- patch-helm.yml
- patch-auth.yml
- patch-echo.yml # Logging to kafka
- patch-repository.yml
#- patch-cf.yml
- patch-http.yml
- patch-redis.yml
- patch-mysql.yml
- patch-armory-agent.yml
- patch-clouddriver-plugin.yml
#- patch-files.yml
#- patch-slack.yml
#- patch-jenkins.yml
- patch-security.yml #
#- patch-opa.yml # old setup

