apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker  # name doesn't matter since this is a patch
spec:
  spinnakerConfig:
      service-settings:
        deck:
          kubernetes:
            serviceAnnotations:
              cloud.google.com/neg: '{"ingress": true}'
              #cloud.google.com/backend-config: '{"default": "https"}'