apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker  # name doesn't matter since this is a patch
spec:
  spinnakerConfig:
    profiles:
      gate:
        security:
          basicform:
            enabled: false
          user:
            name: aaron
            password: aaron1234567
        server:
          servlet:
            context-path: /api
          tomcat:
            protocolHeader: X-Forwarded-Proto
            remoteIpHeader: X-Forwarded-For
            internalProxies: .*
            httpServerPort: X-Forwarded-Port
        redis:
          configuration:
            secure: true
    service-settings:
      gate:
        healthEndpoint: /api/health
        #kubernetes:
          #serviceAnnotations:
           # cloud.google.com/neg: '{"ingress": true}'
            #cloud.google.com/backend-config: '{"default": "https-health"}'
          #podAnnotations:
           # aaron-test: "true"
