apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  #validation:
    #metricStores:
      #enabled: false
  spinnakerConfig:
    config:
      canary:
        enabled: true
        serviceIntegrations:
          - name: aws
            enabled: true
            s3Enabled: true
            accounts:
            - name: aws1
              bucket: aaront-kayenta
              region: us-west-2
              rootFolder: kayenta
              accessKeyId: encrypted:k8s!n:account-secrets!k:aws-access-key-id
              secretAccessKey: encrypted:k8s!n:account-secrets!k:aws-secret-access-key
              supportedTypes:
              - CONFIGURATION_STORE
              - OBJECT_STORE
          - name: newrelic
            enabled: true
            accounts: 
            - name: newrelic1
              endpoint:
                baseUrl: https://insights-api.newrelic.com
              apiKey: encrypted:k8s!n:account-secrets!k:new-relic-api-key
              #defaultScopeKey: default_scope
              #defaultLocationKey: default_location
              applicationKey: 2893088 # account id
              supportedTypes:
              - METRICS_STORE
          - name: prometheus
            enabled: true
            accounts: 
            - name: prom-prod
              endpoint:
                baseUrl: http://prometheus.armory.garreeoke.io
              supportedTypes:
              - METRICS_STORE
            - name: prom-stage
              endpoint:
                baseUrl: http://35.247.88.181:9090
              supportedTypes:
              - METRICS_STORE
        reduxLoggerEnabled: true
        defaultMetricsAccount: prom-prod
        defaultStorageAccount: aws1
        defaultJudge: NetflixACAJudge-v1.0
        defaultMetricsStore: prom-prod
        stagesEnabled: true
        templatesEnabled: true
        showAllConfigsEnabled: true
    #service-settings:
     # kayenta:
      #  kubernetes:
       #   volumes:
        #    - id: gcpjsontoken
         #     type: secret
          #    defaultMode: 420
           #   mountPath: /home/spinnaker/.google