apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      providers:
        aws:
          enabled: true
          accounts:
          - name: aws-dev-1
            requiredGroupMembership: []
            providerVersion: V1
            permissions: {}
            accountId: '795692138404'
            regions:
            - name: us-west-2
            assumeRole: role/Spinnaker-Managed-Role
            lifecycleHooks: []
          primaryAccount: aws-dev-1
          bakeryDefaults:
            baseImages: []
          defaultKeyPairTemplate: '{{name}}-keypair'
          defaultRegions:
          - name: us-west-2
          defaults:
            iamRole: BaseIAMRole
        ecs:
          enabled: true
          accounts:
          - name: ecs-dev-1
            requiredGroupMembership: []
            providerVersion: V1
            permissions: {}
            awsAccount: aws-dev-1
          primaryAccount: ecs-dev-1