apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      artifacts:
        github:
          enabled: true
          accounts:
          - name: garreeoke
            username: garreeokearmory
            token: encrypted:k8s!n:account-secrets!k:github-token
    profiles:
      clouddriver:
        artifacts:
          gitRepo:
            enabled: true
            accounts:
            - name: gitrepo
              token: encrypted:k8s!n:account-secrets!k:github-token