apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  # spec.spinnakerConfig - This section is how to specify configuration spinnaker
  spinnakerConfig:
    # spec.spinnakerConfig.config - This section contains the contents of a deployment found in a halconfig .deploymentConfigurations[0]
    config:
      providers:
        kubernetes:
          enabled: true
          accounts:
            - name: gke-aaron-personal
              kubeconfigFile: encryptedFile:k8s!n:spin-secrets!k:kubeconfig-aaron-armory1
              #serviceAccount: true
              onlySpinnakerManaged: true
              providerVersion: V2
              liveManifestCalls: true
            - name: gke-aaront
              kubeconfigFile: encryptedFile:k8s!n:spin-secrets!k:kubeconfig-aaront1
              onlySpinnakerManaged: true
              liveManifestCalls: true
              providerVersion: V2
              #serviceAccount: true
              #namespaces:
              #- default
              #- acme-air
          primaryAccount: gke-aaront
    #service-settings:
    #  clouddriver:
    #    kubernetes:
    #      serviceAccountName: spinnaker-dev-sa
