apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    config:
      security:
        apiSecurity:
          ssl:
            enabled: false
          overrideBaseUrl: https://spin.armory.garreeoke.io/api
          corsAccessPattern: https://spin.armory.garreeoke.io
        uiSecurity:
          ssl:
            enabled: false
          overrideBaseUrl: https://spin.armory.garreeoke.io