apiVersion: v1
kind: Service
metadata:
  labels:
    app: spin
    cluster: spin-deck-expose
  name: spin-deck-expose
  namespace: spinnaker
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: spin
    cluster: spin-deck
  sessionAffinity: None